version: "3"
services:
  influxdb:
    image: influxdb
    expose:
      - "8086"
    volumes:
      - influxdb:/var/lib/influxdb
  telegraf:
    image: telegraf
    volumes:
      - ./telegraf.conf:/etc/telegraf/telegraf.conf:ro
  dashboard:
    image: grafana/grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana:/var/lib/grafana
  nodered:
    build: ./node-red
    ports:
      - "1880:1880"
    volumes:
      - nodered:/data
  mosquitto:
    image: eclipse-mosquitto
    ports:
      - "1883:1883"
    volumes:
      - mosquitto_data:/mosquitto/data
      - mosquitto_log:/mosquitto/log
      - ./mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf
  dht_room: 
    build: ./trackerdcs
    devices: 
      - /dev/ttyACM0:/dev/ttyACM0
    links: 
      - mosquitto
    command: ['python', 'sensors/dht.py', 'mosquitto', 'room']

volumes:
  influxdb:
  telegraf.conf:
  grafana:
  nodered:
  mosquitto_data:
  mosquitto_log:
  mosquitto.conf:

  