version: "3"
services:
  influxdb:
    image: influxdb:2.0
    restart: always
    expose:
      - "8086"
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=dbuser
      - DOCKER_INFLUXDB_INIT_PASSWORD=password
      - DOCKER_INFLUXDB_INIT_ORG=cms-tedd
      - DOCKER_INFLUXDB_INIT_BUCKET=my-bucket
    volumes:
      - influxdb2:/var/lib/influxdb2
      - ./influxdb/config:/etc/influxdb2
  telegraf:
    image: telegraf
    restart: always
    volumes:
      - ./telegraf.conf:/etc/telegraf/telegraf.conf:ro
  dashboard:
    image: grafana/grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana:/var/lib/grafana
  nodered:
    build: ./node-red
    ports:
      - "1880:1880"
    volumes:
      - nodered:/data
  mosquitto:
    image: eclipse-mosquitto:2.0
    restart: always
    ports:
      - "1883:1883"
    expose:
      - "1883"
    volumes:
      - mosquitto_data:/mosquitto/data
      - mosquitto_log:/mosquitto/log
      - ./mosquitto/config:/mosquitto/config
#  dht_room:
#    build: ./trackerdcs
#    devices:
#      - /dev/ttyACM0:/dev/ttyACM0
#    links:
#      - mosquitto
#    command: ['python', 'sensors/dht.py', 'mosquitto', 'room']
  lv_hmp4040:
    # image: centos:test_dcs_lv_hmp4040
    build: ./low_voltage
    restart: always
    stdin_open: true #docker run -i
    tty: true #docker run -t
    #ports:
    #  - "4000:4000"
    #expose:
    #  - "4000"
    volumes:
      - low_voltage:/usr/app/low_voltage_packages/
  web_server:
    build: ./web_server
    restart: always
    # port must be open even in production as it's a webserver open to outside
    # TODO: setup authentication
    environment:
      - APP_USER=colin
      - APP_PASSWORD=test
    ports:
      - "8001:8000"
    command: ["uvicorn", "web_server.app:app", "--host", "0.0.0.0"]



volumes:
  influxdb2:
  telegraf.conf:
  grafana:
  nodered:
  mosquitto_data:
  mosquitto_log:
  mosquitto.conf:
  low_voltage:

  
