version: "3"
services:
  influxdb:
    image: influxdb
    ports:
      - "8086:8086"
    volumes:
      - influxdb:/var/lib/influxdb
  dashboard:
    image: grafana/grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana:/var/lib/grafana
  nodered:
    image: nodered/node-red
    ports:
      - "1880:1880"
    volumes:
      - nodered:/data
  mosquitto:
    image: eclipse-mosquitto
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - mosquitto_data:/mosquitto/data
      - mosquitto_log:/mosquitto/log
      - ./mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf

volumes:
  influxdb:
  grafana:
  nodered:
  mosquitto_data:
  mosquitto_log:
  mosquitto.conf:
  