version: "3"
services:
  hv:
    build: .
    links:
      - mosquitto
    command: ['python', 'dummy/hv.py', 'hv', 'mosquitto']
  lv:
    build: .
    links:
      - mosquitto
    command: ['python', 'dummy/hv.py', 'lv', 'mosquitto']
  sensor_1:
    build: .
    links:
      - mosquitto
    command: ['python', 'dummy/sensor.py', 'sensor_1', 'mosquitto']
  #lw_volt:
  #  build: .
  #  links:
  #    - mosquitto
  #  command: ['python', 'low_voltage/hmp.py', 'lw_volt', 'mosquitto']
 


