version: "3"
services:
  influxdb:
    image: influxdb
    expose:
      - "8086"
    volumes:
      - influxdb:/var/lib/influxdb
  dashboard:
    image: grafana/grafana
    expose:
      - "3000"
    ports:
      - "3000:3000"
    volumes:
      - grafana:/var/lib/grafana
  nodered:
    # image: nodered/node-red
    build: ./node-red
    expose:
      - "1880"
    ports:
      - "1880:1880"
    volumes:
      - nodered:/data
  mosquitto:
    image: eclipse-mosquitto
    expose:
      - "1883"
    volumes:
      - mosquitto_data:/mosquitto/data
      - mosquitto_log:/mosquitto/log
      - ./mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf

volumes:
  influxdb:
  grafana:
  nodered:
  mosquitto_data:
  mosquitto_log:
  mosquitto.conf:
  