version: "3"
services:
  hv:
    build: ./trackerdcs
    links:
      - mosquitto
    command: ['python', 'dummy/hv.py', 'hv', 'mosquitto']
  lv:
    build: ./trackerdcs
    links:
      - mosquitto
    command: ['python', 'dummy/hv.py', 'lv', 'mosquitto']
  sensor_1:
    build: ./trackerdcs
    links:
      - mosquitto
    command: ['python', 'dummy/sensor.py', 'sensor_1', 'mosquitto']



